### ISSUE TITLE
ruby sdk client not working for me

### ISSUE THREAD

**Issue by muteesa** [signalwire/signalwire-ruby-old#44]
on ruby 2.5.5 
code below just give me blade info but call does not happen. 
 
```
require 'signalwire'

client = Signalwire::Relay::Client.new(project: "xxxx", token: "xxx")
client.connect!

client.on :ready do
          call_handle = client.calling.new_call(from: "+12063855783", to: "+13238946555")
        if call_handle.successful
                call = call_handle.call
        end
          
end
```
 

on ruby 2.3.3
I get error below 

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require': /var/lib/gems/2.3.0/gems/signalwire-2.1.2/lib/signalwire/blade/connection.rb:80: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
      rescue StandardError => e
            ^
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from /var/lib/gems/2.3.0/gems/signalwire-2.1.2/lib/signalwire/blade.rb:8:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require'
        from /var/lib/gems/2.3.0/gems/signalwire-2.1.2/lib/signalwire.rb:10:in <top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in require'
        from call.rb:1:in <main>'
```

please advise.

**Comment by bryanrite** [comment]
@muteesa We will look into this, but you pasted your API Token which is sensitive information to your account, so you should delete it immediately and generate a new one.

**Comment by bryanrite** [comment]
Your first example connects and _then_ sets up the on ready handler... Relay is very fast, so you are probably connected and ready before the handler is setup. Move the `client.connect!` to after the `client.on :ready` declaration. You want to connect _after_ you've setup your handlers.

The second issue, with Ruby 2.3.3 has been fixed in the latest version of the SDK but it is not released yet... you could pull in the master branch by specifying the master branch in your Gemfile:

```
gem 'signalwire', git: 'https://github.com/signalwire/signalwire-ruby.git'
```

until the next Ruby SDK release, which should be imminent.
