### ISSUE TITLE
Failed to reconnect to SignalWire

### ISSUE THREAD

**Issue by crienzo** [signalwire/signalwire-ruby-old#63]
Hours of this log reported:
```
I, [2019-10-22T11:24:07.843204 #19046]  INFO -- SignalWire: Attempting reconnection
I, [2019-10-22T11:24:12.849617 #19046]  INFO -- SignalWire: Attempting reconnection
I, [2019-10-22T11:24:17.855928 #19046]  INFO -- SignalWire: Attempting reconnection
I, [2019-10-22T11:24:22.862424 #19046]  INFO -- SignalWire: Attempting reconnection
```

Followed by this: 
```
Traceback (most recent call last):
        22: from sms_scavenger.rb:126:in `<main>'
        21: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/relay/consumer.rb:62:in `run'
        20: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/relay/client.rb:35:in `connect!'
        19: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:36:in `connect!'
        18: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:48:in `main_loop!'
        17: from /var/lib/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:203:in `run'
        16: from /var/lib/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:203:in `release_machine'
        15: from /var/lib/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1482:in `event_callback'
        14: from /var/lib/gems/2.6.0/gems/faye-websocket-0.10.9/lib/faye/websocket/client.rb:87:in `unbind'
        13: from /var/lib/gems/2.6.0/gems/faye-websocket-0.10.9/lib/faye/websocket/api.rb:152:in `finalize_close'
        12: from /var/lib/gems/2.6.0/gems/faye-websocket-0.10.9/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
        11: from /var/lib/gems/2.6.0/gems/websocket-driver-0.7.1/lib/websocket/driver/event_emitter.rb:38:in `emit'
        10: from /var/lib/gems/2.6.0/gems/websocket-driver-0.7.1/lib/websocket/driver/event_emitter.rb:38:in `each'
         9: from /var/lib/gems/2.6.0/gems/websocket-driver-0.7.1/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
         8: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:53:in `block (2 levels) in main_loop!'
         7: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:135:in `handle_close'
         6: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:44:in `reconnect!'
         5: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:48:in `main_loop!'
         4: from /var/lib/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:171:in `run'
         3: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:59:in `block in main_loop!'
         2: from /var/lib/gems/2.6.0/gems/signalwire-2.2.0/lib/signalwire/blade/connection.rb:64:in `schedule_flush_queues'
         1: from /var/lib/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:328:in `add_timer'
/var/lib/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:328:in `add_oneshot_timer': ran out of timers; use #set_max_timers to increase limit (RuntimeError)
```

**Comment by lpradovera** [comment]
@crienzo this was fixed a couple versions ago, as far as I know. Which version did this happen on? It's possible it is a regression, of course.

**Comment by crienzo** [comment]
Bryan thinks it's 2.2.0 based on the backtrace.

**Comment by bryanrite** [comment]
Using 2.3.0 I can reproduce the same scenario by leaving my client running all night:

```
E, [2019-11-26T09:13:20.734288 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T09:13:25.735995 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T09:13:26.140489 #9911]  INFO -- SignalWire: Blade Session connected with id: ffb330a4-82e0-4c60-9ef9-43e2ef119625
I, [2019-11-26T09:13:32.206986 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T09:13:37.224498 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T09:13:37.234536 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T09:13:42.249634 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T09:13:47.260697 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T09:13:52.310424 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T09:13:57.318825 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T09:13:57.329406 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T11:14:00.117850 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:05.131179 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:10.142842 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:15.157364 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:20.169046 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:25.190447 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:30.182286 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:35.189447 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:40.197333 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:45.212521 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:50.225358 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:14:55.238267 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:15:00.219276 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:15:05.226144 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:15:10.241070 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:15:15.253915 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:15:20.266225 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:15:25.280841 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T11:16:46.687166 #9911]  INFO -- SignalWire: Attempting reconnection
```

Same log repeats forever.

Also see some sequences like this:

```
E, [2019-11-26T16:53:09.716009 #9911] ERROR -- SignalWire: Error setting up Blade connection
I, [2019-11-26T16:53:14.721893 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:53:14.727789 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:15.151449 #9911]  INFO -- SignalWire: Blade Session connected with id: ffb330a4-82e0-4c60-9ef9-43e2ef119625
E, [2019-11-26T16:53:15.378114 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:15.379193 #9911] ERROR -- SignalWire: Relay error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:15.451569 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:15.452942 #9911] ERROR -- SignalWire: Relay error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:16.729128 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:21.733228 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:26.943526 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:53:26.949543 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:31.960004 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:36.968510 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:41.970957 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:46.982613 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:51.989274 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:56.966094 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:01.977652 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:06.986077 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:11.997382 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:17.006684 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:22.032874 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:54:22.040926 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:54:27.026732 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:32.036503 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:54:37.046501 #9911]  INFO -- SignalWire: Attempting reconnection
```

and other sequences like:

```
E, [2019-11-26T16:52:53.574173 #9911] ERROR -- SignalWire: Error setting up Blade connection
I, [2019-11-26T16:52:58.545724 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:52:58.551368 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:03.953685 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:53:03.959209 #9911] ERROR -- SignalWire: We got disconnected!
E, [2019-11-26T16:53:03.959708 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Connection limit reached
I, [2019-11-26T16:53:03.964282 #9911]  INFO -- SignalWire: Blade Session connected with id: ffb330a4-82e0-4c60-9ef9-43e2ef119625
E, [2019-11-26T16:53:03.964620 #9911] ERROR -- SignalWire: Error setting up Blade connection
E, [2019-11-26T16:53:04.315375 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Connection limit reached
I, [2019-11-26T16:53:04.315579 #9911]  INFO -- SignalWire: Blade Session connected with id: ffb330a4-82e0-4c60-9ef9-43e2ef119625
E, [2019-11-26T16:53:04.315695 #9911] ERROR -- SignalWire: Error setting up Blade connection
I, [2019-11-26T16:53:09.324042 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:53:09.330282 #9911] ERROR -- SignalWire: We got disconnected!
E, [2019-11-26T16:53:09.715683 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Connection limit reached
I, [2019-11-26T16:53:09.715912 #9911]  INFO -- SignalWire: Blade Session connected with id: ffb330a4-82e0-4c60-9ef9-43e2ef119625
E, [2019-11-26T16:53:09.716009 #9911] ERROR -- SignalWire: Error setting up Blade connection
I, [2019-11-26T16:53:14.721893 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:53:14.727789 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:15.151449 #9911]  INFO -- SignalWire: Blade Session connected with id: ffb330a4-82e0-4c60-9ef9-43e2ef119625
E, [2019-11-26T16:53:15.378114 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:15.379193 #9911] ERROR -- SignalWire: Relay error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:15.451569 #9911] ERROR -- SignalWire: Blade error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:15.452942 #9911] ERROR -- SignalWire: Relay error occurred, code -32003: Requester validation failed
E, [2019-11-26T16:53:16.729128 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:21.733228 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:26.943526 #9911]  INFO -- SignalWire: Attempting reconnection
E, [2019-11-26T16:53:26.949543 #9911] ERROR -- SignalWire: We got disconnected!
I, [2019-11-26T16:53:31.960004 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:36.968510 #9911]  INFO -- SignalWire: Attempting reconnection
I, [2019-11-26T16:53:41.970957 #9911]  INFO -- SignalWire: Attempting reconnection
```

**Comment by jmdfm** [comment]
First thing to note, is that all of the traces above contain language that was removed in 2.3.1, so these cases were reporting on previous versions of the gem. @lpradovera added an overhaul of how keepalive and reconnects were handled in 2.3.1.

I've tried multiple scenarios in an attempt to recreate this issue and so far, cannot. The client is stable and working as expected. Here is the output from running the client for over 9hours and then bouncing hagrid: 

```
D, [2020-01-15T08:59:03.134192 #20193] DEBUG -- SignalWire: SEND: {
  "method": "blade.ping",
  "params": {
  },
  "jsonrpc": "2.0",
  "id": "36c1fe61-7180-4cbb-a224-a7f71578a551"
}
D, [2020-01-15T08:59:03.207813 #20193] DEBUG -- SignalWire: RECV: {
  "jsonrpc": "2.0",
  "id": "36c1fe61-7180-4cbb-a224-a7f71578a551",
  "result": {
  }
}
W, [2020-01-15T08:59:04.860224 #20193]  WARN -- SignalWire: WS Socket closed!
I, [2020-01-15T08:59:09.863042 #20193]  INFO -- SignalWire: Attempting reconnection
E, [2020-01-15T08:59:17.114860 #20193] ERROR -- SignalWire: Error occurred: Error during WebSocket handshake: Unexpected response code: 502
W, [2020-01-15T08:59:17.115097 #20193]  WARN -- SignalWire: WS Socket closed!
I, [2020-01-15T08:59:22.116931 #20193]  INFO -- SignalWire: Attempting reconnection
E, [2020-01-15T09:00:22.438514 #20193] ERROR -- SignalWire: Error occurred: Error during WebSocket handshake: Unexpected response code: 504
W, [2020-01-15T09:00:22.438723 #20193]  WARN -- SignalWire: WS Socket closed!
I, [2020-01-15T09:00:27.442095 #20193]  INFO -- SignalWire: Attempting reconnection
D, [2020-01-15T09:00:27.769160 #20193] DEBUG -- SignalWire: SEND: {
  "method": "blade.connect",
  "params": {
    "version": {
      "major": 2,
      "minor": 1,
      "revision": 0
    },
    "authentication": {
      "project": "493a3038-919e-4cb9-8fef-fb66c5e6e68f",
      "token": "PTe917dbe76114bfb4c75c3d434681322a3682b329f638e8ba"
    }
  },
  "jsonrpc": "2.0",
  "id": "d6041b7d-32c5-4164-8f0e-c23c66cabe47"
}
D, [2020-01-15T09:00:27.971074 #20193] DEBUG -- SignalWire: RECV: {
  "jsonrpc": "2.0",
  "id": "d6041b7d-32c5-4164-8f0e-c23c66cabe47",
  "result": {
    "session_restored": false,
    "sessionid": "a3a923e4-023d-4ec4-9d76-d8dbea8110af",
    "nodeid": "3205fc68-2fd2-411c-acf4-79a91632ef39",
    "master_nodeid": "00000000-0000-0000-0000-000000000000",
    "authorization": {
      "project": "493a3038-919e-4cb9-8fef-fb66c5e6e68f",
      "expires_at": null,
      "scopes": [
        "calling",
        "messaging",
        "tasking"
      ],
      "signature": "09bde11692154876624eea3557b12d1d38cb4cf1bcd6f75072f2271450bd6cff"
    },
    "routes": [

    ],
    "protocols": [

    ],
    "subscriptions": [

    ],
    "authorities": [

    ],
    "authorizations": [

    ],
    "accesses": [

    ],
    "protocols_uncertified": [
      "signalwire"
    ]
  }
}
I, [2020-01-15T09:00:27.971300 #20193]  INFO -- SignalWire: Blade Session connected with id: f1de25d3-20d1-4513-9103-260ecd6d8ae2
D, [2020-01-15T09:00:27.971380 #20193] DEBUG -- SignalWire: Relay client connected
D, [2020-01-15T09:00:27.976405 #20193] DEBUG -- SignalWire: SEND: {
  "method": "blade.execute",
  "params": {
    "protocol": "signalwire",
    "method": "setup",
    "params": {
      "protocol": "signalwire_09bde11692154876624eea3557b12d1d38cb4cf1bcd6f75072f2271450bd6cff_e784f23a-c7c0-4adf-abf1-72b73fba96c4_493a3038-919e-4cb9-8fef-fb66c5e6e68f"
    }
  },
  "jsonrpc": "2.0",
  "id": "a63c0bd0-8344-4d7a-bf71-7a082ab8c2fd"
}
D, [2020-01-15T09:00:27.976583 #20193] DEBUG -- SignalWire: SEND: {
  "method": "blade.ping",
  "params": {
  },
  "jsonrpc": "2.0",
  "id": "2dcdb69e-07c5-4416-8462-13bb670a65ab"
}
D, [2020-01-15T09:00:28.059828 #20193] DEBUG -- SignalWire: RECV: {
  "jsonrpc": "2.0",
  "id": "33ceb823-7aa5-41da-9dee-f9ee25e30f14",
  "method": "blade.netcast",
  "params": {
    "netcaster_nodeid": "59834dcb-ff36-4f03-b8c0-4ca76f7b74dc",
    "command": "protocol.add",
    "params": {
      "protocol": "signalwire_09bde11692154876624eea3557b12d1d38cb4cf1bcd6f75072f2271450bd6cff_e784f23a-c7c0-4adf-abf1-72b73fba96c4_493a3038-919e-4cb9-8fef-fb66c5e6e68f"
    }
  }
}
D, [2020-01-15T09:00:28.059940 #20193] DEBUG -- SignalWire: RECV: {
  "jsonrpc": "2.0",
  "id": "a63c0bd0-8344-4d7a-bf71-7a082ab8c2fd",
  "result": {
    "requester_nodeid": "3205fc68-2fd2-411c-acf4-79a91632ef39",
    "responder_nodeid": "59834dcb-ff36-4f03-b8c0-4ca76f7b74dc",
    "result": {
      "protocol": "signalwire_09bde11692154876624eea3557b12d1d38cb4cf1bcd6f75072f2271450bd6cff_e784f23a-c7c0-4adf-abf1-72b73fba96c4_493a3038-919e-4cb9-8fef-fb66c5e6e68f"
    }
  }
}
```

As can be seen the client reconnected as soon as Hagrid was replying correctly. 

If this is still happening then I'd like to see the output of `gem which signalwire` in whatever environment this is occurring in, as looking at the code in 2.3.1 and from my testing I don't think this should still be an issue - and even if it was it would present differently by sheer difference of the logging outputs.

**Comment by bryanrite** [comment]
I'm going to close this as its been fixed in the latest version. Thanks!
